apiVersion: v1
kind: Secret
metadata:
  name: grapevine-config
type: Opaque
stringData:
  config.exs: |-
    use Mix.Config

    config :grapevine, Web.Endpoint,
      secret_key_base: "REPLACE"

    config :grapevine, Web.Endpoint,
      http: [port: 4100],
      url: [host: "grapevine.haus", port: 443, scheme: "https"],
      cache_static_manifest: "priv/static/cache_manifest.json"

    config :grapevine, :socket, tls: true

    # Configure your database
    config :grapevine, Grapevine.Repo,
      hostname: "REPLACE",
      username: "REPLACE",
      password: "REPLACE",
      database: "REPLACE",
      pool_size: 10

    config :grapevine, :errors, report: false

    config :grapevine,
      topologies: [
        grapevine: [
          strategy: Cluster.Strategy.Kubernetes.DNS,
          config: [
            service: "gv-grapevine-headless",
            application_name: "grapevine",
            polling_interval: 10_000
          ]
        ],
        grapevine_telnet: [
          strategy: Cluster.Strategy.Kubernetes.DNS,
          config: [
            service: "gv-grapevine-telnet",
            application_name: "telnet",
            polling_interval: 10_000
          ]
        ]
      ]

---
apiVersion: v1
kind: Secret
metadata:
  name: telnet-config
type: Opaque
stringData:
  config.exs: |-
    use Mix.Config

    config :grapevine_telnet, :pubsub, start: true
    config :grapevine_telnet, :errors, report: false

    config :grapevine_telnet,
      topologies: [
        grapevine: [
          strategy: Cluster.Strategy.Kubernetes.DNS,
          config: [
            service: "gv-grapevine-headless",
            application_name: "grapevine",
            polling_interval: 10_000
          ]
        ],
        grapevine_telnet: [
          strategy: Cluster.Strategy.Kubernetes.DNS,
          config: [
            service: "gv-grapevine-telnet",
            application_name: "telnet",
            polling_interval: 10_000
          ]
        ]
      ]
